#!/bin/bash

# Create /etc/sudoers.d/nameserver: <user> <host> = (root) NOPASSWD: /usr/local/bin/nameserver

lo="nameserver 127.0.0.1"

gw="nameserver 192.168.0.1"

google="nameserver 8.8.8.8
nameserver 8.8.4.4"

unlocator="nameserver 185.37.37.37"

case $@ in
	gw)
		chosen=$gw
		;;
	google)
		chosen=$google
		;;
	unlocator)
		chosen=$unlocator
		;;
	*)
		chosen=$lo
		;;
esac

echo "$chosen"

if [ -L /etc/resolv.conf ]; then
	echo "$chosen" > /run/resolvconf/interface/NetworkManager
	resolvconf -u
else
	echo "$chosen" > /etc/resolv.conf
fi

